services:
  - type: web
    name: agente-gimnasio
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GEMINI_API_KEY
        sync: false # Configurar el valor de forma secreta en el Dashboard de Render
